### ISSUE TITLE
Document core/model validation.

### ISSUE THREAD

**Issue by adamcik** [mopidy/mopidy#1150]
Changes in strictness of core and models should be clearly mentioned in the docs before releasing a 1.1

**Comment by tkem** [comment]
Probably not the right place to put this, but I'm in a hurry:

From glancing at https://github.com/mopidy/mopidy/blob/develop/mopidy/models/__init__.py#L50 may I assume that `Ref.type` will be restricted to `album`, `artist`, etc.?
This will break Mopidy-Podcast, which defines its own `Podcast` and `Episode` models, and uses `mopidy.model.Ref`s with type `podcast` and `episode`.

**Comment by adamcik** [comment]
Yes this would break that, so we can either 1) change it to an `Identifier`, i.e. any non unicode string or 2) add `podcast` and `episode` as valid ref types.

Either would be fine with me for the 1.1 release.

**Comment by tkem** [comment]
I think it depends whether we want to support the way Mopidy-Podcast (mis)uses models in general. I mean, do we want/recommended extensions to derive their own types from `ImmutableObject`, or not.
So far, there was no clear recommendation on this in the docs, AFAIK.
If we want to support that (and IMHO it has its benefits, otherwise Mopidy-Podcast wouldn't do that), I think we should also support `Ref`s for custom models. Maybe suggest a naming scheme for third-party Ref types, e.g. `ext_name.model` or something. But, please, no special handling for `podcast` and `episode` ;-)

**Comment by adamcik** [comment]
Ok, well just postpone and avoid breakage by loosing the validation for now.

As for the general case I've been trying to think of all the refs / models we need and it might very be that your suggestion of extension provided ones is more sane. But would greatly increase what frontends need to know about :( One way around this could be if we could have something that takes a model and converts it to "primary" and "secondary" info. So for a track that might be primary "track name", secondary "artist", and for web stream "current song" "station" etc. But I think I'm getting off topic for this issue and there is an other bug where I should be rambling...

**Comment by tkem** [comment]
Yeah, this clearly needs a little more time and thought; so for now, I'd prefer changing `Ref.type` to `Identifier` as you suggested. I suppose I may have gone a little overboard defining my own models for Mopidy-Podcast, but I really like how that allows podcast extensions (itunes, gpodder) to only deal with "domain" objects, and not have to worry about conversion to Mopidy albums/tracks/whatever.

**Comment by adamcik** [comment]
Fixed via edd7afb1745525e64489b12f9c585771506b5edf
