### ISSUE TITLE
Problem with running Mopidy as a service

### ISSUE THREAD

**Issue by npull** [mopidy/mopidy#1190]
Hi
I'm using mopidy for playing music from spotify and using a web extension to control it. I'm using a Synology NAS and got a debian chroot with debootstrap. Everything works flawless with the setup when I run it directly, but when setting it up as a service it wont play any music for me. I get this error in the log;

```2015-05-26 10:13:08,167 ERROR [16284:MainThread] mopidy.audio.gst: GStreamer error: state change failed and some element failed to post a proper error message with the reason for the failure```

Can there be some permission problems somehow?

Here is my config:

```
[logging]
config_file = /etc/mopidy/logging.conf
debug_file = /var/log/mopidy/mopidy-debug.log

[local]
enabled = false

[m3u]
enabled = false

[mpd]
enabled = false

[stream]
enabled = false

[http]
enabled = true
hostname = ::
port = 6680

[spotify]
enabled = true
username = ******
password = ******
bitrate = 320
toplist_countries = SE
```

**Comment by kingosticks** [comment]
Hi, 

This issue tracker is for bug reports and well defined feature requests rather than user support. Please post your question at discuss.mopidy.com where I think there was someone recently trying to do the exact same thing. If you do repost there, please also state if you are using pulseaudio. Thanks.
