### ISSUE TITLE
gapless: Event handling

### ISSUE THREAD

**Issue by adamcik** [mopidy/mopidy#1304]
- [x] Make sure events are fired on stream-changed, not about-to-finish.
- [x] Try and trigger most events off of audio events, not manually.
- [x] Decide if we want to fake old transitions to stopped for the sake of not breaking clients?
- [x] Tags that happen after EOT need to be held until stream-changed.

**Comment by adamcik** [comment]
Most of this is done. Don't think there is much more to do unless we want to fake played -> stopped between tracks.

**Comment by jodal** [comment]
Try the 3-4 most known web clients, if none has any issues with track transitions, close this?

**Comment by adamcik** [comment]
Tags changed during EOT period is wrong. We need to postpone their emission until after stream changed.

**Comment by jcass77** [comment]
As far as I can tell the played -> stopped transition, with the associated event triggers, is the only way for  frontend extensions to reliably detect track changes?

My understanding is that the intention is for backend and frontend extensions to leave track transitions to the core, and just provide the audio URLs for the tracks as core asks for them. 

I've often wondered though if there would be any harm in having core trigger something like ```track_changed_previous``` and ```track_changed_next``` to keep extensions up to date with exactly what is going on.

One use case for this is that, at the moment, it is difficult to tell exactly when a track change is completed successfully and the history is up to date with the details of the track that was changed to. Currently this happens somewhere between ```backend.playback.prepare_change()``` and ```_trigger_track_playback_started()```, but there can also be multiple track transition failures in between.

So I guess what I am asking is if it would make sense to add events triggers for ```track_changed_previous```, ```track_changed_next```, and something like ```history_updated``` in addition to or instead of forcing played -> stopped?

**Comment by adamcik** [comment]
Open a separate bug for this as  that would be adding new events, not preserving our current ones?

As for detecting track changes stream changed is what you should be looking for. But I must say I do want to revamp the events we give out at some point.

**Comment by jcass77** [comment]
I opened #1420 to track the possibility of adding additional events separately.

**Comment by adamcik** [comment]
Updated todo with the hold tags after EOT case. Other items we can probably resolve by saying we won't fix it.

**Comment by adamcik** [comment]
The remaining work for this is to capture all TAGS that happen between `about-to-finish` and `stream-changed`. And to emit them after `stream-changed`. This also implies that code asking what the current tags are should still see the old tags until `stream-changed`. Last corner case is if someone seeks after `about-to-finish` but before `stream-changed`, in which case we start playing the same track again and need to make sure tags are handled correctly.

**Comment by jodal** [comment]
"Tags that happen after EOT need to be held until stream-changed." was fixed by PR #1439.
