### ISSUE TITLE
Postpone set metadata until track is ready

### ISSUE THREAD

**Issue by adamcik** [mopidy/mopidy#1357]
Doing a set metadata inside change track isn't "safe". We need to postpone this until the track is ready. Without this appsrc based backends never propagate metadata to sinks.

**Comment by adamcik** [comment]
Idea fix IMO would be to deprecate the `set_metadata` call and bake this into the appsrc API as a kwarg. But that would be a breaking change.

**Comment by jodal** [comment]
Assigning to @adamcik as he has a working patch that just needs sanity checking for concurrency issues.

**Comment by Leicas** [comment]
Is there a Fix for this issue ? 
I've tried the fix from [#79](https://github.com/mopidy/mopidy-spotify/issues/79) and it only works when I manually change track and sometime (every 5 or 6 songs) when I let songs automatically change.
Thanks in advance !

**Comment by adamcik** [comment]
I haven't completed this yet. We prioritized getting 2.0 out instead of blocking on something which wasn't a regression.

**Comment by allquixotic** [comment]
When using mopidy and mopidy-spotify with git master, I'm having the same problem as Leicas when manually trying to apply my old patch to the new actor.py. I want to use the latest code for numerous good reasons (GST 1.0, many many great bugfixes), but I can't really use it without good support for tags. 

Count me among the users waiting for this to land / willing to test any WIP code that will fix this...!

I think it's probably because set_metadata isn't being called once per track change. And I can't keep a reference to the latest track with set_uri (which I guess is being called when the track changes) because set_uri doesn't create or receive a track object.

Just mucking around in the code like a n00b but not seeing any obvious workaround right now. Looks like gapless has buried the place where this needs to be set.

**Comment by jodal** [comment]
@adamcik Was this fixed by PR #1538?

**Comment by adamcik** [comment]
Yes.

**Comment by brownjd** [comment]
What is the right way to set metadata once you add a uri to the tracklist? How can I specify a track name before playing?
