### ISSUE TITLE
Repurpose "Debian packages" page as a "Running as a service" page

### ISSUE THREAD

**Issue by jodal** [mopidy/mopidy#1398]
Talking about this page: https://docs.mopidy.com/en/latest/debian/

I think most of the page also applies to Mopidy as packaged in Arch, thus this should be repurposed as general docs for running Mopidy as a service.

I'd love for someone running Arch to review the page and tell me what applies to Arch and not.

**Comment by trygveaa** [comment]
> I think most of the page also applies to Mopidy as packaged in Arch, thus this should be repurposed as general docs for running Mopidy as a service.

Good idea. I've gone through the page.

> ***************
> Debian packages
> ***************
> 
> The Mopidy Debian package, ``mopidy``, is available from `apt.mopidy.com
> <http://apt.mopidy.com/>`__ as well as from Debian, Ubuntu and other
> Debian-based Linux distributions.
> 
> Some extensions are also available from all of these sources, while others,
> like Mopidy-Spotify and its dependencies, are only available from
> apt.mopidy.com. This may either be temporary until the package is uploaded to
> Debian and with time propagates to the other distributions. It may also be more
> long term, like in the Mopidy-Spotify case where there is uncertainities around
> licensing and distribution of non-free packages.

Currently, Mopidy is available from the official repos of Arch. No extensions
are available from the official repos, but many extensions are available from
AUR.

> Running as a system service
> ===========================
> 
> The Debian package comes with an init script. It starts Mopidy as a system
> service running as the ``mopidy`` user, which is created by the package.

After the introduction of systemd, it is a bit incorrect to refer to the init
script, since the service file is not a script (this applies for Debian as
well). Otherwise, this paragraph applies for Arch.

> The Debian package version 0.18.3-1 and older starts Mopidy as a system
> service by default. Version 0.18.3-2 and newer asks if you want to run Mopidy
> as a system service, defaulting to not doing so.

No packages in Arch starts automatically after install. To run it as a system
service, you have to start it with systemctl yourself, and to make it start at
boot, you have to enable it.

> If you're running 0.18.3-2 or newer, and you've changed your mind about whether
> or not to run Mopidy as a system service, just run the following command to
> reconfigure the package::
> 
>     sudo dpkg-reconfigure mopidy

Arch doesn't have dpkg-reconfigure or anything similar. To change whether it
runs as a system service, you would run `systemctl start/stop/enable/disable
mopidy`.

> If you're running 0.18.3-1 or older, and don't want to use the init script to
> run Mopidy as a system service, but instead just run Mopidy manually using your
> own user, you need to disable the init script and stop Mopidy by running::
> 
>     sudo update-rc.d mopidy disable
>     sudo service mopidy stop
> 
> This way of disabling the system service is compatible with the improved
> 0.18.3-2 or newer version of the Debian package, so if you later upgrade to a
> newer version, you can change your mind using the ``dpkg-reconfigure`` command
> above.

This doesn't apply to Arch.

> Differences when running as a system service
> ============================================
> 
> If you want to run Mopidy using the init script, there's a few differences
> from a regular Mopidy setup you'll want to know about.
> 
> - All configuration is in :file:`/etc/mopidy`, not in your user's home
>   directory. The main configuration file is :file:`/etc/mopidy/mopidy.conf`.
>   You can do all your changes in this file.
> 
> - Mopidy extensions installed from Debian packages will sometimes install
>   additional configuration files in :file:`/usr/share/mopidy/conf.d/`. These
>   files just provide different defaults for the extension when run as a system
>   service. You can override anything from :file:`/usr/share/mopidy/conf.d/` in
>   the :file:`/etc/mopidy/mopidy.conf` configuration file.
> 
>   Previously, the extension's default config was installed in
>   :file:`/etc/mopidy/extensions.d/`. This was removed with the Debian
>   package mopidy 0.19.4-3. If you have modified any files in
>   :file:`/etc/mopidy/extensions.d/`, you should redo your modifications in
>   :file:`/etc/mopidy/mopidy.conf` and delete the
>   :file:`/etc/mopidy/extensions.d/` directory.
> 
> - The init script runs Mopidy as the ``mopidy`` user. The ``mopidy`` user will
>   need read access to any local music you want Mopidy to play.

This applies to Arch.

> - To run Mopidy subcommands with the same user and config files as the init
>   script uses, you can use ``sudo mopidyctl <subcommand>``. In other words,
>   where you'll usually run::
> 
>       mopidy config
> 
>   You should instead run the following to inspect the system service's
>   configuration::
> 
>       sudo mopidyctl config
> 
>   The same applies to scanning your local music collection. Where you'll
>   normally run::
> 
>       mopidy local scan
> 
>   You should instead run::
> 
>       sudo mopidyctl local scan

sudo is not included in a base install of Arch, though most users will probably
have it installed, and those who don't will probably know what it is and to run
it as root instead. Otherwise, this applies to Arch.

>   Previously, you used ``sudo service mopidy run <subcommand>`` instead of
>   ``mopidyctl``. This was deprecated in Debian package version 0.19.4-3 in
>   favor of ``mopidyctl``, which also work for systems using systemd instead of
>   sysvinit and traditional init scripts.

This doesn't apply to Arch, but since Arch only supports the latest version in
its repos, it probably doesn't matter.

> - Mopidy is started, stopped, and restarted just like any other system
>   service::
> 
>       sudo service mopidy start
>       sudo service mopidy stop
>       sudo service mopidy restart
> 
> - You can check if Mopidy is currently running as a system service by running::
> 
>       sudo service mopidy status

Arch doesn't have the service command. You can do the same things with the
systemctl command, by placing the action before mopidy.

> - Mopidy installed from a Debian package can use Mopidy extensions installed
>   both from Debian packages and with pip. This has always been the case.
> 
>   Mopidy installed with pip can use extensions installed with pip, but
>   not extensions installed from a Debian package released before August 2015.
>   This is because the Debian packages used to install extensions into
>   :file:`/usr/share/mopidy` which is normally not on your ``PYTHONPATH``.
>   Thus, your pip-installed Mopidy would not find the Debian package-installed
>   extensions.
> 
>   In August 2015, all Mopidy extension Debian packages was modified to install
>   into :file:`/usr/lib/python2.7/dist-packages`, like any other Python Debian
>   package. Thus, Mopidy installed with pip can now use extensions installed
>   from Debian.

I think you can mix package and pip installations of Mopidy and extensions
without problems in Arch, but I'm not sure about that. For example is
Mopidy-Spotify from the AUR package installed in
`/usr/lib/python2.7/site-packages/mopidy_spotify/`.

**Comment by jodal** [comment]
Thanks! I think I've incorporated it all into a much cleaned up service page in commit e69ea22cdd2da485da3f215c774a38dffc1fcb27 and 123614ad69bc7c46947e71056e4ac4fcdcae26ad.

Let me know if there's any inaccuracies at https://mopidy.readthedocs.org/en/release-1.1/service/

**Comment by trygveaa** [comment]
I added some small comments to the last commit. Otherwise, it looks good.

**Comment by jodal** [comment]
Fixed in release-1.1 branch. Thanks :-)
