### ISSUE TITLE
"Unit mopidy.service entered failed state" after update to 2.0

### ISSUE THREAD

**Issue by HawkingJan** [mopidy/mopidy#1450]
Hi 
I was using modipy (Version 1.1.2) on a RaspberryPi (Raspbian Jessie) as a service. Everything worked fine (except some issues with songs from YouTube). To test if the new update resolves this issues and profit from other changes I updated to mopidy version 2.0

Now mopidy stoped working. I get

```
● mopidy.service - Mopidy music server
   Loaded: loaded (/lib/systemd/system/mopidy.service; enabled)
   Active: failed (Result: exit-code) since Tue 2016-02-16 00:24:32 CET; 59s ago
  Process: 469 ExecStart=/usr/bin/mopidy --config /usr/share/mopidy/conf.d:/etc/mopidy/mopidy.conf (code=exited, status=203/EXEC)
 Main PID: 469 (code=exited, status=203/EXEC)

Feb 16 00:24:32 wolf systemd[1]: Started Mopidy music server.
Feb 16 00:24:32 wolf systemd[1]: mopidy.service: main process exited, code=exited, status=203/EXEC
Feb 16 00:24:32 wolf systemd[1]: Unit mopidy.service entered failed state.

```

Also an installation of the new gstreamer components
`sudo apt-get install python-gst-1.0 gstreamer1.0-plugins-good gstreamer1.0-plugins-ugly gstreamer1.0-tools
`
nor an restart (of the mopidy service or the whole raspberry) didn't help. What else can I try to fix it?

**Comment by jodal** [comment]
The Debian package upgrade should have taken care of all the required dependencies, so hopefully your `apt-get` command didn't have anything to do.

To get more information about the issue, check the systemd journal for the full service log: `journalctl -u mopidy`

In the future, please use https://discuss.mopidy.com to get help, and only the issue tracker when an actual bug in Mopidy has been identified.

**Comment by HawkingJan** [comment]
> 
The Debian package upgrade should have taken care of all the required dependencies, so hopefully your apt-get command didn't have anything to do.

at least one of the mentioned packages was not yet installed (or at least had to be updated). 

I save the system logs on a ram disk so they are deleted at reboot. The full log is very short
```
-- Logs begin at Tue 2016-02-16 08:46:12 CET, end at Tue 2016-02-16 08:50:26 CET
Feb 16 08:46:15 sys systemd[1]: Starting Mopidy music server...
Feb 16 08:46:15 sys systemd[1]: Started Mopidy music server.
Feb 16 08:46:15 sys systemd[1]: mopidy.service: main process exited, code=exite
Feb 16 08:46:15 sys systemd[1]: Unit mopidy.service entered failed state.

```

**Comment by jodal** [comment]
Sorry, I guess we're still logging mostly to file and not to stdout and the systemd journal.

See if `/var/log/mopidy/mopidy.log` contains more information, and if so upload it to a pastebin and provide the link here.

**Comment by NiclasEriksen** [comment]
I got the same error, and mopidy doesn't get far enough into its startup process to log anything, it seems. Here's the error I got:

`mopidy[14099]: File "/usr/bin/mopidy", line 7, in <module>`
`mopidy[14099]: from mopidy.__main__ import main`
`mopidy[14099]: File "/usr/lib/python2.7/site-packages/mopidy/__main__.py", line 8, in <module>`
`mopidy[14099]: from mopidy.internal.gi import Gst  # noqa: Import to initialize`
`mopidy[14099]: File "/usr/lib/python2.7/site-packages/mopidy/internal/gi.py", line 8, in <module>`
`mopidy[14099]: import gi`
`mopidy[14099]: ImportError: No module named gi`
`systemd[1]: mopidy.service: Main process exited, code=exited, status=1/FAILURE`
`systemd[1]: mopidy.service: Unit entered failed state.`
`systemd[1]: mopidy.service: Failed with result 'exit-code'.`

Turns out I was missing gst-python2, and installing it solved my issue. It wasn't needed until the latest update though, that or it managed just fine with the python3 version.

**Comment by jodal** [comment]
You both had issues starting Mopidy, but I'm afraid the similarity probably stops there as we haven't seen any actual log output from the OP yet. One of you use Raspbian (Debian) and the other Arch (assuming from the gst-python2 package name). It's not useful to track both cases in the same issue.

Generally speaking, if you're ever in doubt if what you see is a new issue or the same as some old issue, always file a new issue and just link to the one you think might be related. Splitting issues isn't support by GitHub in any meaningful way.

Mopidy 2.0 is new major version. The reason it is a major version is mostly because we've changed the major version of our major dependency, GStreamer. If you use Arch packages/AUR, Debian packages or Homebrew, the package system should take care of the upgrade and any new dependencies for you, and it should just work. If you've installed things yourself, e.g. with pip, you'll have to read the [changelog](https://docs.mopidy.com/en/latest/changelog/) and the updated [install docs](https://docs.mopidy.com/en/latest/installation/source/). There are several new system packages that needs to be installed for a pip install of Mopidy 2.0 to work.

I'm closing and locking this issue now. Please use https://discuss.mopidy.com to get help if Mopidy doesn't work for you. If we in the discussions there find actual bugs in Mopidy, we'll file them here in the issue tracker. This isn't to be harsh, but we need to keep the list of issues actionable.
