### ISSUE TITLE
 Mopidy spamming in systemd logs

### ISSUE THREAD

**Issue by VerusGott** [mopidy/mopidy#1545]
Mopidy after start become spamming in logs with one message:

>     INFO     MPD server running at [::ffff:127.0.0.1]:6600
>     INFO     HTTP server running at [::ffff:127.0.0.1]:6680
>     INFO     Starting GLib mainloop
>     INFO     New MPD connection from [::ffff:127.0.0.1]:39910
>     INFO     New MPD connection from [::ffff:127.0.0.1]:39914
>     INFO     New MPD connection from [::ffff:127.0.0.1]:39918
>     INFO     New MPD connection from [::ffff:127.0.0.1]:39922
>     INFO     New MPD connection from [::ffff:127.0.0.1]:39926
>     INFO     New MPD connection from [::ffff:127.0.0.1]:39930
>     INFO     New MPD connection from [::ffff:127.0.0.1]:39934

until I kill mopidy. Because of what it's happening and how I can solve this problem?

**Comment by naglis** [comment]
Hi @VerusGott,

the default logging level for Mopidy is `INFO`. If you are really annoyed by those messages, you could modify your Mopidy systemd service file to add the `--quiet` flag to the Mopidy execution command, which would set the logging level to `WARNING` and significantly reduce the number of logging messages.

**Comment by adamcik** [comment]
Currently I consider this a packaging issues, that is whoever supplies the service files for the distro you are using could set it to `WARNING`. As for you getting connections all the time that would be due to whatever MPD client you are using not mopidy (for instance status bar bling or something getting the current song).

Since there isn't really anything we can do in the code, unless we demote these to `DEBUG` I'm closing this.
