### ISSUE TITLE
local/excluded_file_extensions doesn't work

### ISSUE THREAD

**Issue by realh** [mopidy/mopidy#1584]
The option named above has no effect, because of a bug in mopidy/local/commands.py. On lines 77 to 79 the option is parsed to make a tuple of raw strings, but the check on line 123 treats it as if it were a string containing only one file extension.

As a hacky fix I changed lines 78 and 79 to:

`excluded_file_extensions = ' '.join(excluded_file_extensions).lower()`

and 123 to:

`            elif ('.' + uri.rsplit('.', 1)[1]).lower() in excluded_file_extensions:`

I used `uri` instead of `relpath`, because the latter was tripping up on non-ASCII.

**Comment by realh** [comment]
Anybody still maintaining this?

**Comment by kingosticks** [comment]
https://docs.python.org/2/library/stdtypes.html#str.endswith
>str.endswith(suffix[, start[, end]])
Return True if the string ends with the specified suffix, otherwise return False. **suffix can also be a tuple of suffixes to look for**. With optional start, test beginning at that position. With optional end, stop comparing at that position.

```
>>> 'hello bob'.endswith(tuple(['harry', 'fred', 'bob']))
True
>>> 'hello tim'.endswith(tuple(['harry', 'fred', 'bob']))
False
```
So this all looks fine to me, although it would be nice if we had some tests to prove that.

**Comment by realh** [comment]
Sorry, I didn't realise that about `endswith`. Something seemed to be stopping it from working though, I'll have to check it again.
