### ISSUE TITLE
Allow disabling logging of connections

### ISSUE THREAD

**Issue by tilda** [mopidy/mopidy#1686]
Hi! I have a script on my polybar which I use to get the current song playing on mopidy. Unfortunately, the frequent updates I do (1/second) have consequences.

Whenever mopidy gets a connection, it logs it. I am running it over systemd, and everything goes to syslog. So in syslog I get a lot of useless lines that say "New connection from xx:xx" and it is wasting a lot of space.

So, I'm asking for a way to disable this logging.

Thank you!

**Comment by kingosticks** [comment]
This is already possible since we use regular python logging which is configurable through logging.conf. You can find some examples at https://github.com/pimusicbox/pimusicbox/blob/develop/filechanges/etc/mopidy/logging-debug.conf and https://docs.python.org/2/library/logging.config.html#configuration-file-format

**Comment by tilda** [comment]
I see.

For now, I have disabled logging via the systemd unit.

Thank you!
