### ISSUE TITLE
[Feature request] New backend supporting Funkwhale servers

### ISSUE THREAD

**Issue by EliotBerriot** [mopidy/mopidy#1707]
Hi there! I'm [Funkwhale](https://funkwhale.audio)'s maintainer and I'm thinking about integrating Mopidy and Funkwhale, in the form of a custom mopidy backend or plugin (I'm not sure about your terminology).

In my mind, the Funkwhale server would act as a music provider, as Spotify or Google Music. The backend would talk to the Funkwhale server's API to retrieve music metadata and files (those are served over HTTP).

I still need to have a look at mopidy's codebase to understand how existing backends are implemented, but I wanted to know if that would be the kind of contribution you would consider merging in the main branch.

Any help / guidance / feedback welcome!

**Comment by kingosticks** [comment]
It sounds similar to what the [mopidy-beets](https://github.com/mopidy/mopidy-beets/) *backend extension* provides for the beets music manager. The Gmusic one is another good example, Spotify as well (except for it's special playback requirements). All Mopidy backends are extensions and it's not necessary to merge them into Mopidy core. Otherwise sounds good.

**Comment by EliotBerriot** [comment]
Thank you @kingosticks, that's even better since it means I can maintain this backend in our own repository!
