### ISSUE TITLE
mopidy 2.2.0 does not start

### ISSUE THREAD

**Issue by twenta** [mopidy/mopidy#1709]
When I try to launch mopidy, I get the following error message:

``` python
Traceback (most recent call last):
  File "/usr/bin/mopidy", line 11, in <module>
    load_entry_point('Mopidy==2.2.0', 'console_scripts', 'mopidy')()
  File "/usr/lib/python2.7/dist-packages/mopidy/__main__.py", line 68, in main
    log.setup_logging(config, verbosity_level, args.save_debug_log)
  File "/usr/lib/python2.7/dist-packages/mopidy/internal/log.py", line 54, in setup_logging
    logging.captureWarnings(True)
AttributeError: 'module' object has no attribute 'captureWarnings'
```

Running on:
raspi 2
Linux osmc 4.14.34-4-osmc 
Python 2.7.13

**Comment by jodal** [comment]
This seems very odd:

- `logging.captureWarnings()` is clearly a part of the `logging` module's public API, ref https://docs.python.org/2/library/logging.html#logging.captureWarnings.
- The `mopidy.internal.log` module in Mopidy hasn't changed since v1.1.2 in 2015, ref https://github.com/mopidy/mopidy/commits/release-2.2/mopidy/internal/log.py
