### ISSUE TITLE
Breaking change to HTTP POST API in v2.2.0

### ISSUE THREAD

**Issue by kingosticks** [mopidy/mopidy#1713]
By requiring `Content-Type: application/json` to be set for all HTTP POST requests in #1668, I introduced a breaking change to users of the HTTP POST API in v2.2.0. As pointed out by @tkem [here](https://discourse.mopidy.com/t/after-upgrade-version-2-2-not-connection-from-mopidy-mobile/2793/16)

Users that are unable to set this header would no longer be able to use the HTTP POST API. And even those that could, we should not introduce breaking changes in a feature release. I guess the correct thing to do is have the check configurable and disabled (i.e. the v2.1.0 behaviour) by default, but will a clear recommendation to enable it. At least until the next major release of Mopidy at which point a breaking change is reasonable.

**Comment by jodal** [comment]
In the name of secure defaults, I'd like the current behavior to remain the default.

I'm open to adding a config value to turn the check off, so that the issue can be resolved on either the client side by adding the `Content-Type: application/json` header or on the server side, by turning off the check, whichever is easiest for the end user.

**Comment by kingosticks** [comment]
I'm happy with that. But it'll have to wait until tomorrow.

**Comment by kingosticks** [comment]
https://github.com/mopidy/mopidy/pull/1714

**Comment by jodal** [comment]
Fixed by #1714.
