### ISSUE TITLE
Supported GStreamer versions

### ISSUE THREAD

**Issue by kingosticks** [mopidy/mopidy#1739]
This is to track the current minimum version of GStreamer we require, with the aim of potentially removing some old workarounds and making use of some new features.

Release | GStreamer version
---------- | ------------
| [Debian Jessie](https://packages.debian.org/jessie/libgstreamer1.0-0) | 1.4.4 |
| [Ubuntu 16.04](https://packages.ubuntu.com/xenial/libgstreamer1.0-0) | 1.8.0 |
| [Debian Stretch](https://packages.debian.org/stretch/libgstreamer1.0-0) | 1.10.4 |
| [Ubuntu 18.04](https://packages.ubuntu.com/bionic/libgstreamer1.0-0) | 1.14.0 |
| [Debian Buster](https://packages.debian.org/buster/libgstreamer1.0-0) | 1.14.4 |

Issue/feature | Available from version
---------- | ------------
| Tags after Preroll (#1487) | 1.8.0 |
| `GstPlayer` (doesn't support 'audio-sink' property) | 1.8.0 |
| `GstStream` API  | 1.10.0 |
| `playbin3` and `decodebin3`  | 1.10.0 |
| `playbin3` buffering fixes | 1.12.0 |
| `playbin3` gapless | 1.14.0 |
| `hlssink2` | 1.14.0 |

**Comment by jodal** [comment]
I added this to the v3.0 milestone since what GStreamer versions to support is surely something we should revisit when doing a major release. For Mopidy 3, I think we should require at least GStreamer 1.10. If Buster arrives before Mopidy 3 (lets hope not), GStreamer 1.14 could be the requirement.

However, it might make sense to redefine what versions are supported by Mopidy 2.x too, if that reduces the maintenance burden of that release branch. How much would it help the maintenance of v2.2.x to require GStreamer >= 1.10 instead of >= 1.2.3?

**Comment by jodal** [comment]
Debian Buster is scheduled for 2017-07-06, less than a month away. Thus, we can easily make GStreamer 1.14 the minimum version for all future Mopidy releases. With that declared, all the features in the above table is available to us.

**Comment by kingosticks** [comment]
> Tags after Preroll (#1487)

This one seems to be effecting our handling of HLS streams.

**Comment by jodal** [comment]
With that, we now require GStreamer >= 1.14.0 in Mopidy 3. Now we just need someone to step up to be our new/returned GStreamer master ;-)
