### ISSUE TITLE
Segmentation fault in GStreamer Plugin

### ISSUE THREAD

**Issue by nishanmudalige** [mopidy/mopidy#1884]
I am trying to run mopidy (along with mopidy-spotify) through ncmpcpp on a Mac with OS 10.15.3 (Catalina). I already have `ncmpcpp` working with `mpd` and I'm able to play audio files on a local drive.

I have installed mopidy and `mopidy-spotify` using `homebrew`. I have also installed `gstreamer` and `gstreamer-tools` and set the default python path to run on: `/usr/local/lib/python3.7/site-packages`

I have visited http://mopidy.com/authenticate/ and obtained a client_id and secret and I've edited the `mopidy.conf` file appropriately.

When I run mopidy in the terminal, I get the following error message

```
ERROR: Caught a segmentation fault while loading plugin file:
/usr/local/lib/gstreamer-1.0/libgstpython.so

Please either:
- remove it and restart.
- run with --gst-disable-segtrap --gst-disable-registry-fork and debug.
```

I have read posts on related issues but unfortunately I was not able to use the solutions in them to solve this problem.

Can someone help me resolve this please?

**Comment by kingosticks** [comment]
This is likely to be an installation issue rather than a problem with Mopidy itself and belongs on our [Discourse forum](https://discourse.mopidy.com/) or perhaps at https://github.com/mopidy/homebrew-mopidy. In any case, we ask people read the [troubleshooting documentation](https://docs.mopidy.com/en/latest/troubleshooting/) and provide the standard debug information (*full* log, `mopidy deps`, etc).  

If you are still having this problem can you please open an issue at one of those other places and provide the requested info.
