### ISSUE TITLE
http-extension: allowed_origins doesn't allow 127.0.0.1

### ISSUE THREAD

**Issue by oschade** [mopidy/mopidy#1912]
I run two instances of mopidy at:
http://192.168.178.115:6681
http://192.168.178.115:6682

The first can't access the second one without setting
`allowed_origins = 192.168.178.115:6681`

Because the IP might changed in the future, it would be great to use the localhost:
`allowed_origins = 127.0.0.1:6681`

But this doesn't work.

I thought, I haven't to touch this either, because the docs say
"Same-origin requests (i.e. requests from Mopidy’s web server) are always allowed and so you don’t need an entry for those."

**Comment by kingosticks** [comment]
An [origin](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Origin) 
identifier includes the port. I believe our docs are correct.

I think it may depend on your web browser/client exactly what Host it decides to send. But doesn't this already work if you set your `allowed_origins = 127.0.0.1:6681` and then also access your Mopidy instances using the 127.0.0.1 loopback address rather than 192.168.178.115 address?

**Comment by oschade** [comment]
Good idea! But also not working.
I using the new feature of iris to add a second mopidy-server. I tried to add 127.0.0.1, but this seems not to work in any way:

![grafik](https://user-images.githubusercontent.com/19870969/82117735-94fe9680-9772-11ea-8785-82607d48886c.png)

If a add http://192.168.178.115:6682 as a second server, mopidy throws the following error without setting the allowed_origins_option:

`HTTP request denied for Origin "http://192.168.178.115:6681"`

**Comment by kingosticks** [comment]
I can't really advise on why adding 127.0.0.1 as a new server doesn't work. Seems reasonable to me but this is an Iris feature and I'm not familiar with it at all. I see you already posted in their tracker so maybe follow that part up with @jaedb on there. I am assuming you have correctly set your Mopidy config `http/hostname = ::` for this to work. 

We could try and lookup the Host header value when doing the origins check but I think if we did that we'd support going from a hostname to an IP rather than the reverse way you want.

I *don't* advise doing this, but you can of course disable the check using `http/csrf_protection = false` for testing purposes, or if you understand the risks.

**Comment by oschade** [comment]
> and that this is a regular networking setup rather than some docker network thing (can't help in that case).

I'm testing this on a virtual machine (proxmox, lcx). Maybe this setup leads to this error.

**Comment by kingosticks** [comment]
Yes, I expect it would. You'd have to understand the exact network setup you've implemented there. I'm also pretty sure the proposed solution in the original post would not work. How is something running on an isolated virtual machine supposed to know the other machine it's talking to is also a virtual machine and they are in fact both running on the same host? You also have control of your ip addresses in this setup.

Can we close this?

**Comment by oschade** [comment]
I think it's ok.
Thank you!
