### ISSUE TITLE
Add a DLNA Media Server (DMS) frontend

### ISSUE THREAD

**Issue by jodal** [mopidy/mopidy#52]
We could expose the Mopidy library to [DLNA](wiki) players/renderers if we add a DLNA Media Server (DMS) frontend. This would allow modern TVs and other DLNA compatible players to play music served by Mopidy.

[Coherence](http://coherence.beebits.net/) is a Python implementation of DLNA, and may help us implementing this.

Note: This issue does not concern Mopidy playing music stored on other DLNA Media Servers, like a NAS on your local network. For that feature, see #230.

**Comment by caffinatedmonkey** [comment]
I believe a DLNA renderer connecting to a mopidy server and playing the PCM which would typically come out the speakers would be interesting because most consumers don't have their big speakers hooked up to their PC but their entertainment center which consists of gaming consoles, bluray players and Smart TVs, all of wihch probally have DLNA capabilities. This would allow you to keep your speakers hooked up to your Media Center and have your server offsite, like in your basement.

**Comment by Blackskyliner** [comment]
:+1:

**Comment by jodal** [comment]
https://github.com/tkem/mopidy-dleyna lets Mopidy play music from other DLNA servers, like a NAS.

**Comment by Blackskyliner** [comment]
But sadly not the other way around. As in what the core idea this ticket was about.

**Comment by tkem** [comment]
@Blackskyliner: true, mopidy-dleyna is a backend.

**Comment by liamw9534** [comment]
Worth taking a look at
http://www.digitaltrends.com/home-theater/wireless-speaker-buying-guide/
for an overview of the different technologies being used.

I don't personally have any DLNA speakers but messed around a lot with
Bluetooth speakers which work very well....as long as you don't mind a
slightly restricted range.

I would like to get hold of a pair of WiFi speakers to see how they
work....I hear that many of them are using WiFi Direct now because it
offers a dedicated wireless link allowing much higher audio sample
resolutions to be achieved.  There is also AirPlay (which I think
PulseAudio supports).

**Comment by caffinatedmonkey** [comment]
Its not just speakers. Many TVs and BluRay players support DLNA streaming. It would nice if we could stream audio (video too?) to it of what mopidy is playing.

**Comment by gerroon** [comment]
+1 pretty please

**Comment by jedi7** [comment]
Hi, this feature request is useful to send media to AV receiver for playing, right? It will be very good. Is someone working on it?

**Comment by da-anda** [comment]
I am surprised that mopidy doesn't have a DLNA/upnp backend and also would very welcome it. Until then I will have to look for alternatives for mopidy

**Comment by kingosticks** [comment]
It does have a DLNA backend called Mopidy-DLeyna, this is already mentioned above. This issue was regarding a DLNA frontend, there's more up to date info at https://docs.mopidy.com/en/latest/upnp/ which may suit your usecase if you want to use Mopidy as a renderer alongside some upnp controller you have.

**Comment by da-anda** [comment]
I know it can act as renderer, but since mopidy is a music server, it would make more sense if it could act as UPNP/DLNA server so that you can play music from your mopidy library on any home AV gear and radios. Might stick to Jellyfin for now

**Comment by kingosticks** [comment]
OK, thanks, it is clearer what you mean. I see where you are coming from and I don't disagree it would be good to have but it's worth keeping in mind that in the DLNA sense, Mopidy is (currently) more a DLNA Renderer than a DLNA Media Server. I think what makes the most sense depends what side you are looking from. 

This is another good reason we should implement support for a [HTTP streaming audio output](https://github.com/mopidy/mopidy/issues/56), I had forgotten this usecase and the lack of HTTP streaming is a blocker here (as far as I can see).
