### ISSUE TITLE
Create nightly Debian packages

### ISSUE THREAD

**Issue by pataquets** [mopidy/mopidy#560]
Having a daily built development PPA on Launchpad would ease testing of latest code. Adding a PPA is one of the easiest ways for users to access packages outside their distros and lowering this barrier as much as possible can help attract more testers. Read more [on why](https://help.launchpad.net/Packaging/SourceBuilds).

The way to accomplish this is using Launchpad's "packaging recipes" and code imports from the appropiate branches at Github.

Mopidy's Launchpad page is already set up at:
https://launchpad.net/mopidy

**Comment by jodal** [comment]
I just reviewed Launchpad PPA as a replacement for apt.mopidy.com again, and was pleased to find that you can easily get them to turn on armhf builds for your PPA. Benefits include:

- Automatic builds for amd64, i386 and armhf (ARMv7)
- Separate dists for different Ubuntu versions, so old dists can still keen on using old packages instead of getting errors from new incompatible packages on every dist-upgrade.

Though, there's a couple of major issues:

- No Debian support, so I need to manage that elsewhere.
- I still need to make armhf packages for ARMv6 for Raspberry Pi 1/Raspbian compat, while Debian/Ubuntu armhf only supports ARMv7.

Thus, I'd be stuck with maintaining both apt.mopidy.com and the PPA... and the packages uploaded to Debian/Ubuntu proper. Thus, I currently see little benefit and more work in using PPAs for stable releases.

As for nightlies, it is quite manageable to track Mopidy development with git and virtualenvs, so I think I'll close this bug for now and see if the idea resurfaces in the future.

For proper cleanup, I've removed the empty PPAs under the mopidy organization at Launchpad and revoked @pataquets access.
