### ISSUE TITLE
Auto-generate playlist in local backend based on "new" tracks

### ISSUE THREAD

**Issue by ZenithDK** [mopidy/mopidy#562]
It would be really neat if we could auto-generate a playlist having all the tracks added within the last X days - and label this playlist "New music" or something like it.

I rip my music on a continuous basis, but I sometimes forget about it, and this would be a nice way just to have it at hand and play the playlist.

**Comment by tkem** [comment]
Referring to the original topic of this issue, I think this can be closed now:

- since `local` is planned to be split from Mopidy core, this is essentially an extension issue
- it resembles what `mopidy-local-sqlite` already offers via its `Last Week's/Month's Updates` directories

Any off-topic digressions should have made it into their own issues by now ;-)
