### ISSUE TITLE
Mopidy chokes on huge spotify playlist while using http ws interface

### ISSUE THREAD

**Issue by mrvanes** [mopidy/mopidy#713]
I added (follow) this playlist in spotify online client:
https://play.spotify.com/user/armadamusicofficial/playlist/5lSgExb6yTKfLusGag7bm7
It contains 1000 songs.

When I click the playlist in my MPD client (Rompr, HTTP interface enabled) mopidy fails to load the playlist. If I disable the http interface, the playlist loads instantly.

**Comment by fatg3erman** [comment]
It's probably too late now but for the sake of completeness I'll add my comments. I'm the developer of Rompr and this is indeed rompr's problem.

Rompr does use the HTTP API if it's available. I haven't tried to reproduce this problem but I'm certain I know what the issue is. There's a "problem" - for want of a better word - with mopidy-spotify in that sometimes when you load a playlist the tracks have not been loaded and what you get in the tracklist is:

    [loading...] spotify:track:4u739423894y23nbcy329
    [loading...] spotify:track:43u094nc3u2nc32yn9n32

I've seen this happen sometimes with my personal playlists, and very much more frequently with playlists loaded via the browse function provided by mopidy-spotify and mopidy-spotify-tunigo. As a client/GUI developer my focus is on creating the best (and prettiest) experience for the users, so I implemented a workaround in rompr where I force a playlist lookup with mopidy.playlists.lookup. This returns an array of tracks, and I then just use mopidy.tracklist.add to add that list.. It never occurred to me that anybody would do something as crazy as create a playlist with 1000 tracks;)  and I'd wager my house that either mopidy or the browser is choking on such a huge array. When using the MPD interface, rompr just loads the playlist and trusts to luck.

So from my point of view it would be good if the [loading...] thing could be got rid of, then I could remove the workaround. Or, once the playlists.lookup returns, could I just load the playlist rather than adding all the tracks?

**Comment by jodal** [comment]
Mopidy-Spotify 2.0 is nearing completion and release. All occurrences of `[loading...]` should be gone with it :-)

**Comment by adamcik** [comment]
Is there anything more to do in this bug on the Mopidy side?

**Comment by fatg3erman** [comment]
No, I've stopped doing silly things on my side.

**Comment by adamcik** [comment]
Thanks for the followup.
