### ISSUE TITLE
Unable to reconstruct Spotify's playlists tree structure

### ISSUE THREAD

**Issue by piroxxi** [mopidy/mopidy#953]
Hi,

I'm building an Android application to control a Mopidy instance, running on a Raspberry, through the MPD API. And I'm trying to display the list of Spotify's playlists as a tree structure. But there is no information available to reconstruct such a structure in the list of playlists returned by the "listplaylists" command (http://www.musicpd.org/doc/protocol/playlist_files.html). All playlists name are in the form "Directory SubDirectory PlaylistName" (which works great to load the playlist, but is way too long for printing).

Is there an other way to retrieve my Spotify playlists which would keep a trace of the tree structure ? Otherwise, is it possible to add the information somewhere ?

Thank you for the time you will spend helping me with this issue :) .

Raphaël

**Comment by jodal** [comment]
In Mopidy 0.20 the MPD frontend uses pipe (`|`) instead of space as the folder separator. The relevant commit is a244761abc3f7cc514f8ef62aa6e9f3c81cd6c3b. We can't use the more natural slash, as that's reserved in the MPD protocol.

It's also possible for backends to expose playlists as virtual directories with tracks through the `library.browse()` interface, though that is entirely up to each and every backend. I do however plan to expose the Spotify playlists that way in the upcoming Mopidy-Spotify 2.0.
