### ISSUE TITLE
Extraneous "\" in installing GStreamer for installing from source

### ISSUE THREAD

**Issue by beachamc** [mopidy/mopidy#963]
In the [installation from source](https://docs.mopidy.com/en/latest/installation/source/#install-from-source) there is an extraneous "\" in the instructions on how to install GStreamer. I tried copy and pasting what is currently on there:

```sudo apt-get install python-gst0.10 gstreamer0.10-plugins-good \
    gstreamer0.10-plugins-ugly gstreamer0.10-tools```

I was only able to get this to work by removing the \ like the following:

```sudo apt-get install python-gst0.10 gstreamer0.10-plugins-good 
    gstreamer0.10-plugins-ugly gstreamer0.10-tools```

I haven't tried this for anything other than Ubuntu but it seems as though its probably universal.

**Comment by kingosticks** [comment]
It's a line continuation character.

**Comment by beachamc** [comment]
Sure, I just didn't know if it would be easier to copy and paste without the \. Also, when I was first building this project I wasn't clear that it wasn't supposed to be included in the command and it took me a bit to figure out that it was just indicating a new line.

**Comment by jodal** [comment]
The backslash's purpose is to tell the shell you copy-paste the command into that the command continues on the next line. Without it you would run two commands:

- `sudo apt-get install python-gst0.10 gstreamer0.10-plugins-good`
- `gstreamer0.10-plugins-ugly gstreamer0.10-tools`

Where the last one obviously would fail because it is only two of the arguments to the previous command.

If you copy-paste the backslash, but not the newline character between the two lines (e.g. by copy-pasting one line at the time) then the slash will become an argument to the command, and the command may fail, depending on its expectations. This was probably what you experienced.

**Comment by kingosticks** [comment]
It's a tough one but I think your answer may be slightly better, @jodal!
