### ISSUE TITLE
Current playlist max length limit

### ISSUE THREAD

**Issue by brunorey** [mopidy/mopidy#997]
mpd had a setting for the maximum number of tracks you can add to the currently playing song list, which I can't find in mopidy. 

I use mopidy in an office environment and every now and then someone new accidentally adds all local songs (~50.000) to the list and mopidy becomes extremely slow, almost unresponsive. There should be a limit to avoid this.

**Comment by adamcik** [comment]
This also reminds me that I think ncmcpp segfaults at 10000 songs, and that the mpd protocol specifies this as the limit. So yes we should probably do something about this.

**Comment by michaelhblackburn** [comment]
I'd like to look into this; is this something that needs to be done in core/tracklist.py or core/playlist.py, do you think?

**Comment by jodal** [comment]
The current playlist (MPD terminology) / tracklist (MPRIS terminology) / play queue (yet another terminology) is in `core/tracklist.py` :-)

**Comment by jodal** [comment]
My suggestion for solving this is:

- Make `core.tracklist.add()` check the length of the tracklist against a max of 10000.
- If it fails, raise an exception. We should maybe add a `CoreError` with a subclass, `TracklistFull`, for this case in `mopidy/exceptions.py`?
- Have the MPD frontend catch that exception and return the same response as the original MPD server does when its tracklist reaches 10000 tracks.
- Optionally, add a config to be able to adjust the limit to be *lower* than 10000, but not higher. Maybe add a new "[core]" section to the config and name it `core/max_tracklist_length` with a default of 10000?

**Comment by brunorey** [comment]
I think there should be a new value in configuration with a max value of 10000 and core.tracklist.add() should check that the new length is not greater than the configured value. 

Tracklist shouldn't "know" the max value 10000, it belongs in config validations. 

I agree with the rest of your suggestions, I only think the fourth point you mention should be more important (not "optionally").

**Comment by RonaldZ** [comment]
The main problem we're having with this issue is pulling a value from the config files. Was trying to look through the code for a previous example of it being done but didn't come up with anything.

Any suggestions to push us in the right direction?

**Comment by jodal** [comment]
Uhm, looks like the core layer doesn't have access to the config. I guess we've never needed it there before. I'll see if I can get that fixed.

**Comment by RonaldZ** [comment]
That was a quick response. Thank you.

**Comment by RonaldZ** [comment]
Ok, going to un-retcon my retcon from IRC. I seem to have run into an issue that is different than what is described in the recent commit "Add a [core] config section"

The traceback:
  File "/home/ronald/.Envs/mopidy/bin/mopidy", line 9, in <module>
    load_entry_point('Mopidy==1.0.7', 'console_scripts', 'mopidy')()
  File "/home/ronald/Repositories/mopidy-dev/mopidy/mopidy/__main__.py", line 78, in main
    create_file_structures_and_config(args, extensions_data)
  File "/home/ronald/Repositories/mopidy-dev/mopidy/mopidy/__main__.py", line 179, in create_file_structures_and_config
    default = config_lib.format_initial(extensions)
  File "/home/ronald/Repositories/mopidy-dev/mopidy/mopidy/config/__init__.py", line 88, in format_initial
    defaults.extend(e.get_default_config() for e in extensions)
  File "/home/ronald/Repositories/mopidy-dev/mopidy/mopidy/config/__init__.py", line 88, in <genexpr>
    defaults.extend(e.get_default_config() for e in extensions)
AttributeError: 'ExtensionData' object has no attribute 'get_default_config'

I get this error with and without my changes. Stepped through the for loop in line 88 of config/__init__.py to see if I could find out what is blowing up. Didn't figure out much. The for loop would cut out on the third iteration each time. If the debug variable print out is to be trusted, and if the loop is iterating in the same order as given as the print out, then that'd be the https extension.

Went over each extension after the https one looked ok, and not finding any problems. Typically this problem is a space/indentation issue but flake8 local testing gives me the green light.

Any ideas?

**Comment by jodal** [comment]
Fixed by the merge of #1225.
